export const popularCountries = [
    "United States",
    "United Kingdom",
    "Canada",
    "Australia",
    "Germany",
    "France",
    "India",
    "Pakistan",
    "Bangladesh",
    "China",
    "Japan",
    "South Korea",
    "Indonesia",
    "Brazil",
    "Mexico",
    "Russia",
    "Italy",
    "Spain",
    "Netherlands",
    "Turkey",
    "Philippines",
    "Nigeria",
    "South Africa",
    "Egypt",
    "Argentina",
  ];
  