export const ROUTES = {
  PAGES_ROUTES: {
    HOME: "/",
    SHORTS: "/shorts",
    HISTORY: "/feed/history",
    PLAYLISTS: "/feed/playlists",
    LIKEDVIDEOS: "/like-videos",
    DISLIKEDVIDEOS: "/dislike-videos",
    VIDEO_UPLOADS: "/all-videos",
    SUBSCRIPTIONS: "/subscriptions",
    COMMUNITY_POSTS: "/community-posts",
    WATCH_LATER: "/watch-later",
    SETTINGS: "/settings",
    PROFILE: "/feed/profile",
    ACCOUNT: "/account",
    ACCOUNT_SECURITY: "/account/security",
    SIGN_UP: "/sign-up",
    SIGN_IN: "/sign-in",
    SIGN_OUT: "/sign-out",
    CHANNEL: "/channel",
    USER_UPDATE: "/user-update",
  },
  API_ROUTES: {
    USER_DATA_FETCH: "/api/user",
    USER_ASSETS_UPLOAD: "/api/user/upload",
    USER_AUTH_SIGN_IN: "/api/user/auth/sign-in",
    USER_AUTH_SIGN_OUT: "/api/user/auth/sign-out",
    USER_AUTH_SIGN_UP: "/api/user/auth/sign-up",
    USER_NAME_CHECK: "/api/user/check-username",
    USER_ACCNT_DELETE: "/api/user/delete-account",
    USER_PROFILE_FETCH: "/api/user/profile",
    USER_ACCNT_UPDATE: "/api/user/update",
    USER_ACCNT_PASSWD_UPDATE: "/api/user/update/passwd",
    USER_ACCNT_VERIFY: "/api/user/verify",
  },
};
