export const ROUTES = {
  PAGES_ROUTES: {
    HOME: "/",
    SHORTS: "/shorts",
    HISTORY: "/feed/history",
    PLAYLISTS: "/feed/playlists",
    LIKEDVIDEOS: "/like-videos",
    DISLIKEDVIDEOS: "/dislike-videos",
    VIDEO_UPLOADS: "/all-videos",
    SUBSCRIPTIONS: "/subscriptions",
    COMMUNITY_POSTS: "/community-posts",
    WATCH_LATER: "/watch-later",
    SETTINGS: "/settings",
    PROFILE: "/feed/profile",
    ACCOUNT: "/account",
    ACCOUNT_SECURITY: "/account/security",
    SIGN_UP: "/sign-up",
    SIGN_IN: "/sign-in",
    SIGN_OUT: "/sign-out",
    CHANNEL: "/channel",
    USER_UPDATE: "/user-update",
  },
  API_ROUTES: {
    USER_ASSETS_UPLOAD: "/api/user/upload",
    USER_PROFILE_FETCH: "/api/user/profile",
  },
};
