import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { auth } from "@/app/api/auth/[...nextauth]/configs";
import ClientRootLayout from "./clientRootLayout";
import { Toaster } from "@/components/ui/sonner"
import { getUserFromRedis } from "@/lib/getUserFromRedis";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "streamX - Enjoy the world",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  const userId = session?.user?._id;
  if(userId){
    const userData = await getUserFromRedis(userId);
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <AuthProvider session={session}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ClientRootLayout>
            {children}
          </ClientRootLayout>
          <Toaster />
        </body>
      </AuthProvider>
    </html>
  );
}