name: CI - Production Build (Next.js)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Validate
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - name: 📥 Install Dependencies
        run: npm ci

      - name: 🔍 Run Lint (Optional)
        run: npm run lint
        continue-on-error: true  # Set false if you want to fail build on lint errors

      - name: 🔎 Type Check (Optional)
        run: npm run type-check
        continue-on-error: true  # Set false if you want to fail build on TS errors
        
      - name: 📄 Create .env.production from GitHub secret
        run: echo "${{ secrets.ENV_FILE }}" > .env.production
        
      - name: 🛠️ Build Next.js App
        run: npm run build
        env:
          NODE_ENV: production
